# Generated by Django 3.2.8 on 2021-12-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentteam',
            name='placement',
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
